USE ZION
GO

--QUERY TO CREATE TABLE FOR REPORT SHEET
CREATE TABLE REPORT_SHEET(REG_NO VARCHAR(7) PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
ENGLISH INT NULL,
MATHS INT NULL,
PHYSICS INT NULL,
CHEMISTRY INT NULL,
[GEOGRAPHY] INT NULL,
[ECONS/FUR_MATHS] INT NULL,
[TD/AGRIC] INT NULL,
COMPUTER_STUDIES INT NULL,
WAZOBIA INT NULL,
TOTAL INT NULL,
AVERAGE DECIMAL(5,2) NULL,
CONSTRAINT CK_REGNO CHECK(DATALENGTH(REG_NO)= 7) -- CONSTRAINT TO ENSURE REGISTRATION NUMBER IS EXACTLY 7 CHARACTERS
)
GO

--INSERT VALUES INTO THE REPORT_SHEET TABLE
INSERT INTO REPORT_SHEET(REG_NO, NAME, ENGLISH, MATHS, PHYSICS, CHEMISTRY, [GEOGRAPHY],[ECONS/FUR_MATHS],[TD/AGRIC],COMPUTER_STUDIES, WAZOBIA)
VALUES('#######', '*******', 51, 51, 63, 60, 74, 54, 46, 81, 72)
GO

--CREATE A TRIGGER TO CALCULATE TOTAL AND AVERAGE SCORES
CREATE TRIGGER TR_REPORT_SHEET
ON REPORT_SHEET
FOR INSERT
AS
BEGIN
	UPDATE REPORT_SHEET SET TOTAL = MATHS + ENGLISH + PHYSICS + CHEMISTRY + [GEOGRAPHY] + [ECONS/FUR_MATHS] + [TD/AGRIC] + COMPUTER_STUDIES + WAZOBIA
	UPDATE REPORT_SHEET SET AVERAGE = TOTAL / 4.00
END
GO